### PR TITLE
remove Var module

### PR DESCRIPTION
**Pull request by mimoo**
Looks like the `Var` module might have been a vestige of the past? It's currently nothing more than an `int`:

https://github.com/MinaProtocol/mina/blob/develop/src/lib/crypto/kimchi_backend/common/var.ml#L3

### CODE REVIEW

**Review by mrmr1993 — COMMENTED** [review]
Looks good, but can you make a companion PR for the mina side?

**Comment by mimoo** [comment]
https://github.com/MinaProtocol/mina/pull/12093

**Review by mrmr1993 — APPROVED** [review]

**Comment by mimoo** [comment]
!ci-build-me

**Comment by mimoo** [comment]
olol

**Comment by mimoo** [comment]
wrong repo, thx!

**Pull request merged**
