### PR TITLE
removing unused proof API from snarky

### PR DESCRIPTION
**Pull request by mimoo**

### CODE REVIEW

**Comment by imeckler** [comment]
Looks like you need to reformat with `make reformat` -- also build will probably fail on the examples

**Comment by mimoo** [comment]
> Looks like you need to reformat with make reformat

what's the rationale behind `app/reformat` btw? Why not use the default formatting?

> build will probably fail on the examples

that is probably true, I'd be really good if we could get build to work in CI to test PRs like this one

**Comment by mimoo** [comment]
rebasing

**Comment by mimoo** [comment]
Looks like this: [Proof_system](https://github.com/o1-labs/snarky/blob/015426c2e1dddda5724644e21043c4c41c12d45c/src/toplevel.ml#L245-L245)

and this: [Proof_system](https://github.com/o1-labs/snarky/blob/015426c2e1dddda5724644e21043c4c41c12d45c/src/toplevel.ml#L418-L418)

are not building correctly. I could just delete these patterns from the match but is it really what we want to do here?

**Comment by mimoo** [comment]
removing `src/toplevel.ml` after discussions

**Comment by mrmr1993** [comment]
You'll also need to remove references to `Toplevel` elsewhere before this will compile.

**Review by mrmr1993 — APPROVED** [review]
Amazing! I've been looking forward to killing this for ages :D

**Comment by mimoo** [comment]
looks like I can't merge this myself

**Pull request merged**
