### PR TITLE
add asm function

### PR DESCRIPTION
**Pull request by mimoo**
this exposes the ASM functionality of kimchi added in https://github.com/o1-labs/proof-systems/pull/831

See https://github.com/MinaProtocol/mina/pull/12125 to see how it's used in tests

### CODE REVIEW

**Review by mrmr1993 — CHANGES_REQUESTED** [review]
There's no need for this to be exposed here. It's better to let this be just the DSL, and update the underlying `Plonk_constraint_system` to expose it

**Comment by mimoo** [comment]
my understanding was that I can't use it from plonk_constraint_system if I don't expose it in the back end interface, because I won't be able to call it. But maybe I'm wrong, I'll have to check your way

**Comment by mrmr1993** [comment]
> The same should have been done with digest as well no?

Yes please. It would be good to delete the whole constraint system interface from the output of `Make`.

**Comment by mimoo** [comment]
Actually, I thought a bit more about it, and if we want to replace snarky with snarky-rs, then any functionalities exposed by plonk_constraint_system should be exposed by snarky instead

**Comment by mrmr1993** [comment]
Not sure I agree. Snarky-rs will run a circuit to create a constraint system, just like snarky does. The methods that the constraint system exposes are completely unrelated to snarky, it's just responsible for creating it.

**Comment by mimoo** [comment]
sg, closing!

**Pull request closed without merging**
