### PR TITLE
Add a website

### PR DESCRIPTION
**Pull request by mrmr1993**
This PR
* adds a docusaurus website
* takes out some of the example content
* sets up the footer with our relevant social links etc.
* adds a docs file (actually just the contents of `README.md` for now)
* adds a script for generating API docs (`make website`)
  - adding generated docs will be a separate PR to keep this one managable

To try it out
* install docusaurus (`npm install docusaurus`)
* `(cd website/website; npm start)` to start the server
* open `http://localhost:3000/`

### CODE REVIEW

**Comment by bkase** [comment]
Looks like a good start! (obviously we'll need to flesh out the landing page before we deploy this)

**Comment by mrmr1993** [comment]
@bkase Thanks! Do we have a logo that we can use? Would be good to swap out the docusaurus logo 😅

**Comment by bkase** [comment]
I think @imeckler and Harold have a high quality version of the logo we're using in discord

**Comment by mrmr1993** [comment]
Added a CI test and updated with the logo and colour scheme. Screenshots:

screenshot from 2019-03-07 18-22-47
screenshot from 2019-03-07 18-22-52
screenshot from 2019-03-07 18-23-31
screenshot from 2019-03-07 18-24-36
screenshot from 2019-03-07 18-24-44
screenshot from 2019-03-07 18-26-08
screenshot from 2019-03-07 18-26-20
screenshot from 2019-03-07 18-26-27

**Pull request merged**
